### ISSUE TITLE
A transaction on 0xProtocol.

### ISSUE THREAD

**Issue by DataFi-EigenPhi** [eigenphi/AwesomeTx#1]
https://etherscan.io/tx/0x0804e35ffcd0b94d911bc5b7fed563abc8fffc67d0780ec8a689d8a61ffd0aec

**Comment by TheMichaelMatch** [comment]
Hello there, thanks for participating in our previously concluded "Awesome Transactions Bounty" program. In other news, we have a great update for you! It's the new analyzing tool called "EigenTx" which you can use to analyze and dissect your submission and other transactions you deem necessary or intriguing! Follow the link below to enjoy the experience.

https://tx.eigenphi.io/
