### ISSUE TITLE
curve sandwich high roller

### ISSUE THREAD

**Issue by gryndamere** [eigenphi/AwesomeTx#11]
https://etherscan.io/tx/0xada54289d2a5556b2aa8f6ca26317a0649397fff8babd7a5bb6f6270815c8a8e - 1
https://etherscan.io/tx/0x29afdc352692a037a80d871fce20dd7515b70313860a63220c57529022ab22c7 - getting sandwiched 
https://etherscan.io/tx/0x125f8af2870daa4b00f55e3b6b2d368a409e3b056b1ab6a2dbbcd1a554bd79e1 - 3

**Comment by DataFi-EigenPhi** [comment]
Hi @gryndamere, thanks for your participation. The community and our team all benefit from your partaking. 

You may have noticed that we are working on a complex transaction analyzer. Here is the link to the tool parsing the tx you submitted. 

[The analyzer link](https://tx.eigenphi.io/analyseTransaction?chain=Ethereum&tx=0xada54289d2a5556b2aa8f6ca26317a0649397fff8babd7a5bb6f6270815c8a8e%2C0x29afdc352692a037a80d871fce20dd7515b70313860a63220c57529022ab22c7%2C+0x125f8af2870daa4b00f55e3b6b2d368a409e3b056b1ab6a2dbbcd1a554bd79e1&rankdir=LR)

This tool is still in the private test phase that only opens to a few users. 

You are more than welcome to join the specified discord channel for it. We look forward to your suggestions on features, bugs, and improvements. C'mon in!

[https://discord.gg/kmjNKFvV](https://discord.gg/kmjNKFvV)

**Comment by TheMichaelMatch** [comment]
Hey bud, congratulations on becoming a winner of this competition. To receive your reward, kindly send a private message to me on Discord with proof of identity or related information. RockBottom#9099(MichaelOG|EigenPhi) is my Discord handle. Cheers!

**Comment by gryndamere** [comment]
awesome lads! thanks for the dissection, the tool looks great!

**Comment by TheMichaelMatch** [comment]
Hello there, thanks for participating in our just concluded "Awesome Transactions Bounty" program. In other news, we have a great update for you! It's the new analyzing tool called "EigenTx" which you can use to analyze and dissect your submission and other transactions you deem necessary or intriguing! Follow the link below to enjoy the experience.

https://tx.eigenphi.io/
