### ISSUE TITLE
A reentrancy attack using NFTs

### ISSUE THREAD

**Issue by htadashi** [eigenphi/AwesomeTx#18]
https://etherscan.io/tx/0x05d65e0adddc5d9ccfe6cd65be4a7899ebcb6e5ec7a39787971bcc3d6ba73996

Tenderly debug: https://dashboard.tenderly.co/tx/mainnet/0x05d65e0adddc5d9ccfe6cd65be4a7899ebcb6e5ec7a39787971bcc3d6ba73996

**Comment by DataFi-EigenPhi** [comment]
Hi @htadashi, thanks for your participation. The community and our team all benefit from your partaking. 

You may have noticed that we are working on a complex transaction analyzer. Here is the link to the tool parsing the tx you submitted. 

[*The analyzer link*
](https://tx.eigenphi.io/analyseTransaction?chain=Ethereum&tx=0x05d65e0adddc5d9ccfe6cd65be4a7899ebcb6e5ec7a39787971bcc3d6ba73996&eliminateTransferBySameFromToToken=on&rankdir=LR)
This tool is still in the private test phase that only opens to a few users. 

You are more than welcome to join the specified discord channel for it. We look forward to your suggestions on features, bugs, and improvements. C'mon in!

[https://discord.gg/kmjNKFvV](https://discord.gg/kmjNKFvV)

**Comment by htadashi** [comment]
@DataFi-EigenPhi it was a pleasure, as I love your work. And I also will be delighted to experiment this new tool :)

**Comment by htadashi** [comment]
Thanks! I sent you a message there :)
